import { useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Project = { name: string; initials: string; description: string; status: 'On track' | 'At risk' | 'Planning'; progress: number; members: number; due: string; tone: string }

const initialProjects: Project[] = [
  { name: 'Website redesign', initials: 'WR', description: 'Refresh the marketing site and docs', status: 'On track', progress: 72, members: 8, due: 'Oct 24', tone: 'blue' },
  { name: 'Mobile app v2', initials: 'MA', description: 'A faster, more personal mobile experience', status: 'At risk', progress: 48, members: 12, due: 'Nov 02', tone: 'orange' },
  { name: 'Q4 campaign', initials: 'QC', description: 'Launch plan for the holiday campaign', status: 'Planning', progress: 18, members: 5, due: 'Nov 18', tone: 'green' },
]
const navItems = [['Overview', '⌂'], ['My work', '✓'], ['Projects', '▦'], ['Calendar', '□'], ['Reports', '↗']]
const initialTasks = [
  { label: 'Review homepage concepts', project: 'Website redesign', checked: false },
  { label: 'Share research notes with team', project: 'Mobile app v2', checked: true },
  { label: 'Approve campaign budget', project: 'Q4 campaign', checked: false },
]

function App() {
  const [activeNav, setActiveNav] = useState('Overview')
  const [projects, setProjects] = useState(initialProjects)
  const [tasks, setTasks] = useState(initialTasks)
  const [search, setSearch] = useState('')
  const [showProjectForm, setShowProjectForm] = useState(false)
  const [showInvite, setShowInvite] = useState(false)
  const [showNotifications, setShowNotifications] = useState(false)
  const [newProject, setNewProject] = useState('')
  const [toast, setToast] = useState('')
  const filteredProjects = projects.filter((project) => `${project.name} ${project.description}`.toLowerCase().includes(search.toLowerCase()))
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2800) }
  const createProject = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!newProject.trim()) return
    setProjects((current) => [...current, { name: newProject.trim(), initials: newProject.trim().slice(0, 2).toUpperCase(), description: 'A new space for your team to do great work', status: 'Planning', progress: 0, members: 1, due: 'Set a due date', tone: 'purple' }])
    setNewProject(''); setShowProjectForm(false); notify('Project created successfully')
  }

  return (
    <div className="app-shell">
      <aside className="sidebar"><div className="brand"><span className="brand-mark">N</span><span>northstar</span></div><div className="workspace-switcher"><span className="workspace-avatar">A</span><span><b>Acme Inc.</b><small>Growth workspace</small></span><span className="chevron">⌄</span></div><nav className="main-nav" aria-label="Main navigation"><p className="nav-label">Workspace</p>{navItems.map(([label, icon]) => <button key={label} className={activeNav === label ? 'nav-item active' : 'nav-item'} onClick={() => setActiveNav(label)}><span className="nav-icon">{icon}</span>{label}{label === 'My work' && <span className="nav-count">3</span>}</button>)}<p className="nav-label space-top">Manage</p><button className="nav-item" onClick={() => notify('Team settings opened')}><span className="nav-icon">⚙</span>Settings</button><button className="nav-item" onClick={() => notify('Help center opened')}><span className="nav-icon">?</span>Help center</button></nav><div className="sidebar-bottom"><div className="upgrade-card"><span className="spark">✦</span><b>Unlock your potential</b><p>Get more from your workspace with Pro.</p><button onClick={() => notify('Upgrade flow started')}>Explore Pro <span>→</span></button></div><div className="user-row"><span className="user-avatar">JD</span><span><b>Jordan Davis</b><small>Admin</small></span><button aria-label="Open user menu" onClick={() => notify('Profile menu opened')}>•••</button></div></div></aside>
      <main className="main-content"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><span>/</span><b>{activeNav}</b></div><div className="top-actions"><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search anything..." /><kbd>⌘ K</kbd></label><button className="icon-button notification-button" aria-label="Notifications" onClick={() => setShowNotifications((current) => !current)}>♧<i></i></button><button className="invite-button" onClick={() => setShowInvite(true)}><span>+</span> Invite</button></div>{showNotifications && <div className="notification-popover"><b>Notifications</b><p><span className="dot blue-dot"></span>Mia commented on Website redesign</p><p><span className="dot green-dot"></span>Your weekly report is ready</p><button onClick={() => setShowNotifications(false)}>Mark all as read</button></div>}</header>
        <div className="content-wrap"><div className="page-heading"><div><p className="eyebrow">Monday, October 16, 2024</p><h1>Good morning, Jordan <span>✦</span></h1><p className="subheading">Here is what is happening across your workspace today.</p></div><button className="primary-button" onClick={() => setShowProjectForm(true)}><span>+</span> New project</button></div>
          <section className="metric-grid" aria-label="Workspace metrics"><div className="metric-card"><div className="metric-top"><span>Active projects</span><span className="metric-icon blue-icon">▦</span></div><strong>{projects.length}</strong><small><em className="up">↗ 12%</em> vs last month</small></div><div className="metric-card"><div className="metric-top"><span>Tasks completed</span><span className="metric-icon green-icon">✓</span></div><strong>84</strong><small><em className="up">↗ 8.4%</em> vs last month</small></div><div className="metric-card"><div className="metric-top"><span>Team members</span><span className="metric-icon purple-icon">♙</span></div><strong>24</strong><small><em className="up">↗ 2</em> new this month</small></div><div className="metric-card"><div className="metric-top"><span>Hours tracked</span><span className="metric-icon orange-icon">◷</span></div><strong>312<span className="metric-unit">h</span></strong><small><em className="down">↘ 3.2%</em> vs last month</small></div></section>
          <div className="section-heading"><div><h2>Project overview</h2><p>Keep an eye on your team's progress.</p></div><button className="text-button" onClick={() => setActiveNav('Projects')}>View all projects <span>→</span></button></div><section className="project-table"><div className="table-head"><span>Project</span><span>Status</span><span>Progress</span><span>Members</span><span>Due date</span><span></span></div>{filteredProjects.length ? filteredProjects.map((project) => <div className="project-row" key={project.name}><div className="project-name"><span className={`project-avatar ${project.tone}`}>{project.initials}</span><span><b>{project.name}</b><small>{project.description}</small></span></div><span className={`status ${project.status.toLowerCase().replace(' ', '-')}`}><i></i>{project.status}</span><div className="progress-wrap"><div className="progress-bar"><span style={{ width: `${project.progress}%` }}></span></div><small>{project.progress}%</small></div><div className="member-stack"><span>JD</span><span className="member-two">MK</span><small>+{project.members - 2}</small></div><span className="due-date">{project.due}</span><button className="row-menu" aria-label={`Actions for ${project.name}`} onClick={() => notify(`${project.name} actions opened`)}>•••</button></div>) : <div className="empty-state">No projects match “{search}”.</div>}</section>
          <div className="lower-grid"><section className="panel tasks-panel"><div className="panel-heading"><div><h2>My tasks</h2><p>Tasks that need your attention</p></div><button className="more-button" aria-label="More task options" onClick={() => notify('Task options opened')}>•••</button></div><div className="task-list">{tasks.map((task, index) => <label className={task.checked ? 'task checked' : 'task'} key={task.label}><input type="checkbox" checked={task.checked} onChange={() => setTasks((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, checked: !item.checked } : item))} /><span className="checkmark">✓</span><span><b>{task.label}</b><small>{task.project}</small></span><time>{index === 0 ? 'Today' : index === 1 ? 'Tomorrow' : 'Oct 20'}</time></label>)}</div><button className="panel-link" onClick={() => setActiveNav('My work')}>View all tasks <span>→</span></button></section><section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Updates from your team</p></div><button className="more-button" aria-label="More activity options" onClick={() => notify('Activity options opened')}>•••</button></div><div className="activity-list"><div className="activity-item"><span className="activity-avatar teal">MC</span><p><b>Mia Chen</b> completed <strong>Design system audit</strong><small>12 minutes ago · Website redesign</small></p></div><div className="activity-item"><span className="activity-avatar coral">AR</span><p><b>Alex Rivera</b> added a comment to <strong>Onboarding flow</strong><small>1 hour ago · Mobile app v2</small></p></div><div className="activity-item"><span className="activity-avatar yellow">SK</span><p><b>Sam Kim</b> created a new project <strong>Q4 campaign</strong><small>3 hours ago · Workspace</small></p></div></div><button className="panel-link" onClick={() => notify('All activity loaded')}>View all activity <span>→</span></button></section></div>
        </div></main>
      {showProjectForm && <div className="modal-backdrop" onClick={() => setShowProjectForm(false)}><form className="modal" onSubmit={createProject} onClick={(event) => event.stopPropagation()}><button type="button" className="modal-close" aria-label="Close" onClick={() => setShowProjectForm(false)}>×</button><span className="modal-kicker">NEW PROJECT</span><h2>Start something great</h2><p>Give your new project a name. You can customize the details later.</p><label>Project name<input autoFocus value={newProject} onChange={(event) => setNewProject(event.target.value)} placeholder="e.g. Product launch" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowProjectForm(false)}>Cancel</button><button type="submit" className="primary-button">Create project</button></div></form></div>}
      {showInvite && <div className="modal-backdrop" onClick={() => setShowInvite(false)}><form className="modal invite-modal" onSubmit={(event) => { event.preventDefault(); setShowInvite(false); notify('Invitation sent') }} onClick={(event) => event.stopPropagation()}><button type="button" className="modal-close" aria-label="Close" onClick={() => setShowInvite(false)}>×</button><span className="modal-kicker">GROW TOGETHER</span><h2>Invite your team</h2><p>Bring the right people into your workspace.</p><label>Email address<input type="email" autoFocus required placeholder="name@company.com" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowInvite(false)}>Cancel</button><button type="submit" className="primary-button">Send invite</button></div></form></div>}
      {toast && <div className="toast"><span>✓</span>{toast}</div>}
    </div>
  )
}

export default App
